// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/entityapi/entity.proto

/*
Package entityapi is a generated protocol buffer package.

It is generated from these files:
	pkg/entityapi/entity.proto

It has these top-level messages:
*/
package entityapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Entity service

type EntityClient interface {
}

type entityClient struct {
	cc *grpc.ClientConn
}

func NewEntityClient(cc *grpc.ClientConn) EntityClient {
	return &entityClient{cc}
}

// Server API for Entity service

type EntityServer interface {
}

func RegisterEntityServer(s *grpc.Server, srv EntityServer) {
	s.RegisterService(&_Entity_serviceDesc, srv)
}

var _Entity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entityapi.Entity",
	HandlerType: (*EntityServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/entityapi/entity.proto",
}

func init() { proto.RegisterFile("pkg/entityapi/entity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 62 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xc8, 0x4e, 0xd7,
	0x4f, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x4c, 0x2c, 0xc8, 0x84, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0xe1, 0xe2, 0x46, 0x1c, 0x5c, 0x6c, 0xae, 0x60, 0x4e, 0x12, 0x1b, 0x58, 0xce,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x9f, 0xde, 0x66, 0x39, 0x00, 0x00, 0x00,
}
